version: '3.4'

services:
  devvesgtest:
    image: devvesgtest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: devvesg
      POSTGRES_PASSWORD: devvesg
