import { QuestionType, ScoreType } from '../enums';
import { SeedData } from './interface';
import { SeedQuizQuestion } from './quiz-question';

export const QUIZ_QUESTIONS_GENERAL: SeedData<SeedQuizQuestion> = {
  PRIMARY_REGION: {
    data: {
      name: 'What is the primary region of your organization (United States)?',
      description: '',
      questionType: QuestionType.TEXT,
      sortOrder: 1,
    },
  },
  ARE_YOU_GOVT_ENTITY: {
    data: {
      name: 'Are you a government entity?',
      description: '',
      questionType: QuestionType.RADIO,
      sortOrder: 2,
    },
    relationships: {
      options: ['ARE_YOU_GOVT_ENTITY_YES', 'ARE_YOU_GOVT_ENTITY_NO'],
    },
  },
  SUBCONTRACTORS: {
    data: {
      name: 'Do you have subcontractors (city)?',
      description: '',
      questionType: QuestionType.RADIO,
      sortOrder: 3,
    },
    relationships: {
      options: ['SUBCONTRACTORS_YES', 'SUBCONTRACTORS_NO'],
    },
  },
  INDUSTRY: {
    data: {
      name: 'What Industry is your organization in? ',
      description: '',
      questionType: QuestionType.MULTI_SELECT_DROPDOWN,
      sortOrder: 4,
    },
    relationships: {
      options: [
        'INDUSTRY_TYPE_AEROSPACE',
        'INDUSTRY_TYPE_AGRICULTURE_FISHING',
        'INDUSTRY_TYPE_AGRICULTURE_LIVESTOCK',
        'INDUSTRY_TYPE_AGRICULTURE_MEAT',
        'INDUSTRY_TYPE_AGRICULTURE_TIMBER',
        'INDUSTRY_TYPE_AGRICULTURE_TOBACCO',
        'INDUSTRY_TYPE_CE',
        'INDUSTRY_TYPE_CP',
        'INDUSTRY_TYPE_CR',
        'INDUSTRY_TYPE_CRT',
        'INDUSTRY_TYPE_CS',
        'INDUSTRY_TYPE_CONSTRUCTION',
        'INDUSTRY_TYPE_DEFENCE',
        'INDUSTRY_TYPE_EDUCATION_ALT',
        'INDUSTRY_TYPE_EDUCATION_HIGH',
        'INDUSTRY_TYPE_EDUCATION_PRE',
        'INDUSTRY_TYPE_EDUCATION_PRI',
        'INDUSTRY_TYPE_EDUCATION_SP',
        'INDUSTRY_TYPE_EDUCATION_VOC',
        'INDUSTRY_TYPE_ENERGY_COAL',
        'INDUSTRY_TYPE_ENERGY_EP',
        'INDUSTRY_TYPE_ENERGY_NU',
        'INDUSTRY_TYPE_ENERGY_PET',
        'INDUSTRY_TYPE_ENERGY_RENEW',
        'INDUSTRY_TYPE_ENTERTAINMENT_AMUSE',
        'INDUSTRY_TYPE_ENTERTAINMENT_ANI',
        'INDUSTRY_TYPE_ENTERTAINMENT_CIR',
        'INDUSTRY_TYPE_ENTERTAINMENT_EM',
        'INDUSTRY_TYPE_ENTERTAINMENT_FILM',
        'INDUSTRY_TYPE_ENTERTAINMENT_GAMBLING',
        'INDUSTRY_TYPE_ENTERTAINMENT_GAME',
        'INDUSTRY_TYPE_ENTERTAINMENT_MEDIA',
        'INDUSTRY_TYPE_ENTERTAINMENT_MUSIC',
        'INDUSTRY_TYPE_ENTERTAINMENT_SPORTS',
        'INDUSTRY_TYPE_ENTERTAINMENT_TALENT',
        'INDUSTRY_TYPE_ENTERTAINMENT_THEATRE',
        'INDUSTRY_TYPE_FINANCIAL_ACCOUNT',
        'INDUSTRY_TYPE_FINANCIAL_BANKS',
        'INDUSTRY_TYPE_FINANCIAL_INSURANCE',
        'INDUSTRY_TYPE_FINANCIAL_INVEST',
        'INDUSTRY_TYPE_FINANCIAL_STOCK',
        'INDUSTRY_TYPE_FOOD_AGRI',
        'INDUSTRY_TYPE_FOOD_PROCESS',
        'INDUSTRY_TYPE_FOOD_SER',
        'INDUSTRY_TYPE_FOOD_TECH',
        'INDUSTRY_TYPE_FOOD_GROC',
        'INDUSTRY_TYPE_FOOD_HORTI',
        'INDUSTRY_TYPE_FOOD_MANU',
        'INDUSTRY_TYPE_HEALTH',
        'INDUSTRY_TYPE_HOSPITALITY',
        'INDUSTRY_TYPE_INFO',
        'INDUSTRY_TYPE_MANUFACTURE_END',
        'INDUSTRY_TYPE_MANUFACTURE_MACHINE',
        'INDUSTRY_TYPE_MANUFACTURE_RAW',
        'INDUSTRY_TYPE_MASS_MEDIA_BROAD',
        'INDUSTRY_TYPE_MASS_MEDIA_FILM',
        'INDUSTRY_TYPE_MASS_MEDIA_INTERNET',
        'INDUSTRY_TYPE_MASS_MEDIA_MUSIC',
        'INDUSTRY_TYPE_MASS_MEDIA_NEWS',
        'INDUSTRY_TYPE_MASS_MEDIA_PUB',
        'INDUSTRY_TYPE_MUNCI',
        'INDUSTRY_TYPE_OTHER',
        'INDUSTRY_TYPE_PHARMA',
        'INDUSTRY_TYPE_SOV_NAT',
        'INDUSTRY_TYPE_TELE',
        'INDUSTRY_TYPE_TRANSPORT',
        'INDUSTRY_TYPE_WATER_DRINK',
        'INDUSTRY_TYPE_WATER_WASTE',
      ],
    }
  }
};
