export const VERTICALS = [
  'Aerospace',
  'Agriculture',
  'Agriculture - Livestock',
  'Agriculture - Fishing',
  'Agriculture - Timber',
  'Agriculture - Tobacco',
  'Agriculture - Meat & Dairy',
  'Chemical Manufacturing',
  'Pharmaceuticals',
  'Computers',
  'Computers - Software',
  'Computers - Peripherals',
  'Computers - Repair',
  'Computers - Retail',
  'Construction',
  'Defense',
  'Education',
  'Education - Preschools/Daycares',
  'Education - Primary & Secondary',
  'Education - Higher',
  'Education - Vocational',
  'Education - Special',
  'Education - Alternative',
  'Energy',
  'Energy - Electrical Power',
  'Energy - Petroleum/Oil',
  'Energy - Coal',
  'Energy - Nuclear',
  'Energy - Renewable',
  'Entertainment',
  'Entertainment - Amusement Parks',
  'Entertainment - Animation',
  'Entertainment - Circus',
  'Entertainment - Event Management',
  'Entertainment - Film',
  'Entertainment - Gambling',
  'Entertainment - Game Manufacturing',
  'Entertainment - Media',
  'Entertainment - Music',
  'Entertainment - Sports Management and Event Promotion',
  'Entertainment - Talent Agency',
  'Entertainment - Theatre Production',
  'Financial',
  'Financial - Banks and Credit Unions',
  'Financial - Insurance',
  'Financial - Accountancy',
  'Financial - Stock Brokerages',
  'Financial - Investment Funds',
  'Food',
  'Food - Agriculture',
  'Food - Horticulture',
  'Food - Manufacturing',
  'Food - Food Processing',
  'Food - Grocery',
  'Food - Food Service',
  'Food - Food Technology',
  'Health Care',
  'Hospitality',
  'Information',
  'Manufacturing',
  'Manufacturing - End Products',
  'Manufacturing - Raw Materials',
  'Manufacturing - Machining',
  'Mass Media',
  'Mass Media - Broadcasting',
  'Mass Media - Film',
  'Mass Media - Internet',
  'Mass Media - Music',
  'Mass Media - News',
  'Mass Media - Publishing',
  'Telecommunications',
  'Transport',
  'Water',
  'Water - Drinking Water',
  'Water - Wastewater',
  'Other',
  'Municipality',
  'Sovereign Nation',
];
