{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "-100"
  {{- end }}
{{- end }}
